//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.Pages {
	
	
	public partial class reademail {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button accountButton;
		
		protected System.Web.UI.WebControls.Button logoutButton;
		
		protected System.Web.UI.WebControls.Button returnInbox;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl warningdiv;
		
		protected System.Web.UI.WebControls.TextBox timestamp;
		
		protected System.Web.UI.WebControls.TextBox sender;
		
		protected System.Web.UI.WebControls.TextBox recipient;
		
		protected System.Web.UI.WebControls.TextBox messageContent;
	}
}
